version: '3.6'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
      - registry-certs:/certs
      - registry-auth:/auth
    networks:
      - gitlab
volumes:
  registry-data:
  registry-certs:
  registry-auth:
networks:
  gitlab: