version: '3.6'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./volumes/data:/var/lib/registry
      - ./volumes/certs:/certs
      - ./volumes/auth:/auth
    networks:
      - gitlab
networks:
  gitlab: